[package]
name = "models"
version = "0.1.0"
authors = ["salibert"]
edition = "2018"


[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dotenv = "0.9.0"
actix-web = "0.7"
actix = "0.7"
diesel = { version = "1.4.1", features = ["postgres", "r2d2"] }